### ISSUE TITLE
Wordlists and requirements.txt not downloadable

### ISSUE THREAD

**Issue by veikk0** [NorthwaveSecurity/wikiraider#1]
The wordlist download links in the README don't lead to downloadable text files but to git-lfs pointers. After downloading, installing, and running `git lfs fetch` in a cloned repository, the command fails with the following message:

    batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
    error: failed to fetch some objects from 'https://github.com/NorthwaveSecurity/wikiraider.git/info/lfs'

Furthermore, it seems that all text files in the repository are tracked by git-lfs, not just the wordlists. This includes requirements.txt, so the dependencies to run the program can't actually be installed.

If the wordlists are too large to store in git, it'd probably be better to make them available as zip files using the release feature of Github.

**Comment by tijme** [comment]
I've just fixed it by migrating to SharePoint. Check the updated readme for the download links.
